image:
  - Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

install:
  - cmd: git submodule update --init --recursive
  - cmd: curl --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.1.106.0/windows/VulkanSDK-1.1.106.0-Installer.exe
  - cmd: dir
  - cmd: .\VulkanSDK.exe /S

build_script:
  - cmd: mkdir build && cd build
  - cmd: cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%configuration% ..
  - cmd: cmake --build . --target ALL_BUILD --config %configuration%
