image:
  - Visual Studio 2017

platform: x64

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version
  - cmd: curl --silent --show-error --output VulkanSDK.exe https://vulkan.lunarg.com/sdk/download/1.0.51.0/windows/VulkanSDK-1.0.51.0-Installer.exe
  - cmd: .\VulkanSDK.exe /S

branches:
  only:
    - master

install:
  - cmd: git submodule update --init --recursive

build_script:
  - cmd: mkdir build && cd build
  - cmd: cmake -G "Visual Studio 15 2017" -DCMAKE_BUILD_TYPE=%configuration% ..
  - cmd: cmake --build . --target ALL_BUILD --config %configuration%
